### ISSUE TITLE
Duplicate plugin/preset detected

### ISSUE THREAD

**Issue by dmytro-ipatii** [mike-north/professional-ts#34]
Hi.
I've installed the 'professional-ts' project, followed all instructions about how install it, but when I'm trying to run command "yarn dev" I've got a big fat error in my console.

`/Users/Dima/PROJECTS /THEORY/Front-End Masters/TS Production-Grade/professional-ts/src/index.js: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.`

`  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]`

`Duplicates detected are:
[
  {
    "alias": "/Users/Dima/PROJECTS /THEORY/Front-End Masters/TS Production-Grade/professional-ts/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
    "dirname": "/Users/Dima/PROJECTS /THEORY/Front-End Masters/TS Production-Grade/professional-ts",
    "ownPass": false,
    "file": {
      "request": "@babel/plugin-proposal-class-properties",
      "resolved": "/Users/Dima/PROJECTS /THEORY/Front-End Masters/TS Production-Grade/professional-ts/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
    }
  },
  {
    "alias": "base$1",
    "options": {
      "loose": "#__internal__@babel/preset-env__prefer-false-but-true-is-ok-if-it-prevents-an-error"
    },
    "dirname": "/Users/Dima/PROJECTS /THEORY/Front-End Masters/TS Production-Grade/professional-ts",
    "ownPass": false
  }
]`

**Comment by pawelnvk** [comment]
Check if removing `@babel/plugin-proposal-class-properties` from `.babelrc` will fix it for you.
https://github.com/mike-north/professional-ts/blob/master/.babelrc#L7

**Comment by dmytro-ipatii** [comment]
Awesome! It works, thanks!
